# Generated by Django 5.2.10 on 2026-01-28 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psrs_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('REMOTE', 'Remote'), ('DAR_ES_SALAAM', 'Dar_es_salaam'), ('OTHERS', 'Others')], default='OTHERS', max_length=40)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='JobsApplications',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('cover_leter', models.FileField(upload_to='cover_leter/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to='psrs_auth.userprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='psrs_job.job')),
            ],
            options={
                'verbose_name': 'Job_application',
                'verbose_name_plural': 'Job_applications',
                'ordering': ['-primary_key'],
            },
        ),
    ]
